# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  distro-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Configure NET 6
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          # Specify the NuGet source to restore packages from
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: |
            6.x.x
            7.x.x
        env:
          # Use repository secret key to authenticate personal NuGet
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
          
      - name: Restore
        run: dotnet restore Distro
      
      - name: Build
        run: dotnet build Distro --configuration Release
    
      - name: Test
        run: dotnet test **/*/Shared.Test.csproj --verbosity normal
