name: Build and Test packages

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  distro-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 9.x.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
          
      - name: Restore
        run: dotnet restore Distro
      
      - name: Build
        run: dotnet build Distro --configuration Release
    
      - name: Test
        run: dotnet test --verbosity normal
        env:
          TEST_IMGBBCLIENT_APIKEY: ${{secrets.TEST_IMGBBCLIENT_APIKEY}}
