# This is a basic workflow to help you get started with Actions

name: Build, Test, Pack and Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  distro-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Configure NET 6
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          # Specify the NuGet source to restore packages from
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.x.x
        env:
          # Use repository secret key to authenticate personal NuGet
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
          
      - name: Restore
        run: dotnet restore Distro
      
      - name: Build
        run: dotnet build Distro --configuration Release
    
      - name: Test
        run: dotnet test **/*/Shared.Test.csproj --verbosity normal

      - name: Publish NuGet
        run: | # | character makes the "run" property multi-line, so we can put multiple commands in the same step
          dotnet pack Distro --configuration Release --no-restore
          dotnet nuget push "./**/*.nupkg" --skip-duplicate  --no-symbols --api-key ${{secrets.NUGET_TOKEN}}
          rm -rf __out
